lstm = Sequential()
lstm.add(LSTM(10,input_shape=(1,10)))
lstm.add(Dense(1))
feature_vec = lstm(lstm_input_sequences)
feature_vec = np.array(feature_vec)
# np.reshape(feature_vec,(68,10,10))
vnn = Sequential()
vnn.add(Input(1,68))
vnn.add(Dense(units=10,activation='sigmoid'))
loss_fn = keras.losses.MeanSquaredError()
vnn.compile(loss='mse',optimizer='adam',metrics=['accuracy'])
print(vnn.summary())
vnn.fit(feature_vec,output_prob_matrix,32,100)